Added @putmapping in FileStorageController class and updateFiles() FileStorageService class to updating file on Minio server
Sunbird-RC/sunbird-rc-core pull request #212
Opened 2023-04-07 07:12 UTC by chopadetejaswini

… FileStorageService class to edit the document contents and updating edited file  on Minio.

2023-04-10 07:22 UTC, varadeth approved these changes

2023-04-10 07:22 UTC, varadeth commented on java/registry/src/main/java/dev/sunbirdrc/registry/controller/FileStorageController.java
> +    @GetMapping(value = "/api/v1/{entity}/{entityId}/{property}/documents/{documentId}", produces = MediaType.APPLICATION_OCTET_STREAM_VALUE)//it returns binary data, such as a file or an image.
remove comment

2023-04-10 07:22 UTC, varadeth commented on java/registry/src/main/java/dev/sunbirdrc/registry/controller/FileStorageController.java
> +
remove this new lines

2023-04-10 07:22 UTC, varadeth commented on java/registry/src/main/java/dev/sunbirdrc/registry/service/FileStorageService.java
> +		String[] split = requestedURI.split(versionDelimiter);//splits this URI into two parts using the delimiter "/v1/" by calling the split() method on the requestedURI string.
remove comments

2023-04-10 07:22 UTC, varadeth commented on java/registry/src/main/java/dev/sunbirdrc/registry/service/FileStorageService.java
> +		String uuid = UUID.randomUUID().toString();//generates a unique identifier using the UUID.randomUUID() method,
remove comments

2023-04-10 07:22 UTC, varadeth commented on java/registry/src/main/java/dev/sunbirdrc/registry/service/FileStorageService.java
> +	public void update(InputStream inputStream, String objectName) throws Exception//inputStream is a file to be saved,Returns a new InputStream that reads no bytes. The returned stream is initially ope
this function is not used anywhere?

2023-04-10 07:22 UTC, varadeth commented on java/registry/src/main/java/dev/sunbirdrc/registry/service/FileStorageService.java
> +				for (MultipartFile file1 : files) {
please check the logic here. if file is not present, this will create a add it

2023-06-15 11:06 UTC, varadeth requested changes

2023-06-15 11:06 UTC, varadeth commented on java/registry/src/main/java/dev/sunbirdrc/registry/service/FileStorageService.java
> +				String objectName = objectPath;
this can be removed and objectPath itself can be used

2023-06-30 13:50 UTC, varadeth requested changes
Resolve conflicts

2023-07-25 10:19 UTC, holashchand requested changes
Please resolve all the comments and also add unit and e2e tests

2023-07-25 10:19 UTC, holashchand commented on java/registry/src/main/java/dev/sunbirdrc/registry/controller/RegistryController.java
> +            registryService.deleteEntityById(shard, entityType,apiMessage.getUserID(), recordId.getUuid());
Why calling same request twice? delete one

2023-07-25 10:19 UTC, holashchand commented on java/registry/src/main/java/dev/sunbirdrc/registry/dao/RegistryDaoImpl.java
> +           // logger.debug("Vertex with ID {} deleted", databaseProvider.getId(vertex));
debug log should be there

2023-07-25 10:19 UTC, holashchand commented on java/registry/src/main/resources/application.yml
> +  hard_delete_enabled: true
Get it from an environment variable and set default to false

2023-07-25 10:19 UTC, holashchand commented on java/registry/src/main/resources/application.yml
> +  client-secret: ${sunbird_sso_admin_client_secret:652cc530-1a59-48ef-849f-02e96ff3b3a8}
revert this change, secret should not be committed

2023-07-25 10:19 UTC, holashchand commented on java/registry/src/main/resources/application.yml
> +  bucketname: ${filestorage_bucket_key:issuance}
revert these changes too

2023-07-25 10:19 UTC, holashchand commented on java/sunbirdrc-actors/src/main/java/dev/sunbirdrc/actors/ElasticSearchActor.java
> +                }
add break for case "UPDATE"

2024-01-16 05:48 UTC, srprasanna commented
@holashchand please review, add whatever is missing and close this please.

2024-01-25 11:50 UTC, closed without merging

2024-01-25 11:50 UTC, holashchand commented
Closing since it contains irrelevant changes