Added @putmapping in FileStorageController class and updateFiles() in…
Sunbird-RC/sunbird-rc-core pull request #220
Opened 2023-04-19 12:16 UTC by chopadetejaswini

Support hard delete in core

2023-04-24 11:35 UTC, tejash-jl commented on java/registry/src/main/java/dev/sunbirdrc/registry/controller/FileStorageController.java
> +                                                    HttpServletRequest httpServletRequest) throws ServerException, InsufficientDataException, ErrorResponseException, IOException, NoSuchAlgorithmExcep
don't throw any exception from controller,
handle all the error inside

2023-04-24 11:35 UTC, tejash-jl commented on java/registry/src/main/java/dev/sunbirdrc/registry/controller/FileStorageController.java
> +            registryHelper.authorize(entity, entityId, httpServletRequest);// authorize() to authorize the request
remove all comments like this,
https://www.freecodecamp.org/news/code-comments-the-good-the-bad-and-the-ugly-be9cc65fbf83/

2023-04-24 11:35 UTC, tejash-jl commented on java/registry/src/main/java/dev/sunbirdrc/registry/service/FileStorageService.java
> +	public void update(InputStream inputStream, String objectName) throws Exception//inputStream is a file to be saved,Returns a new InputStream that reads no bytes. The returned stream is initially ope
where is the func used?

2023-05-21 15:03 UTC, varadeth requested changes

2023-05-21 15:03 UTC, varadeth commented on java/registry/src/main/java/dev/sunbirdrc/registry/service/FileStorageService.java
> +				for (MultipartFile file1 : files) {
I would say lets not save the file if it is not present. Lets only update the file if present or else throw appropriate error

2023-06-26 11:10 UTC, closed without merging