Support hard delete in core
Sunbird-RC/sunbird-rc-core pull request #221
Opened 2023-04-19 12:33 UTC by chopadetejaswini

2023-04-24 11:24 UTC, tejash-jl commented on java/registry/src/main/java/dev/sunbirdrc/registry/controller/RegistryEntityController.java
> +    //@RequestHeader annotation binds request header values to method parameters
remove comments

2023-04-24 11:24 UTC, tejash-jl commented on java/registry/src/main/resources/application.yml
> +  client-secret: ${sunbird_sso_admin_client_secret:652cc530-1a59-48ef-849f-02e96ff3b3a8}
dont push these values

2023-04-24 11:24 UTC, tejash-jl commented on java/registry/src/main/resources/application.yml
> +  providerName: ${search_providerName:dev.sunbirdrc.registry.service.ElasticSearchService}
keep the default values

2023-04-24 11:24 UTC, tejash-jl commented on java/registry/src/main/java/dev/sunbirdrc/registry/service/impl/RegistryServiceImpl.java
> +            elasticService.hardDeleteEntity(parentEntityType,entityRootId);
why is this function called here?

2023-04-24 11:24 UTC, tejash-jl commented on java/elastic-search/src/main/java/dev/sunbirdrc/elastic/ESMessage.java
> +    public void setDeleteType(String deleteType)
who will set the deleteType?
why do we need this?

2023-06-26 11:58 UTC, varadeth requested changes

2023-06-26 11:58 UTC, varadeth commented on docker-compose.yml
> +     - /home/ttpl-rt-49/sunbird_rc_core/demo-education-registry/schemas:/home/sunbirdrc/config/public/_schemas
remove this change

2023-06-26 11:58 UTC, varadeth commented on docker-compose.yml
> +    - ./imports:/opt/jboss/keycloak/imports
remove this change

2023-06-26 11:58 UTC, varadeth commented on java/elastic-search/src/main/java/dev/sunbirdrc/elastic/ESMessage.java
> +
can these lines also me removed

2023-06-26 11:58 UTC, varadeth commented on java/registry/src/main/resources/application.yml
> +  accesskey: ${filestorage_access_key:admin}
remove this change

2023-06-26 11:58 UTC, varadeth commented on java/registry/src/main/resources/application.yml
> +  HARD_DELETE_ENABLED: true
please update this with small case

2023-06-26 11:58 UTC, varadeth commented on java/registry/src/main/java/dev/sunbirdrc/registry/service/impl/RegistryServiceImpl.java
> +    @Value("${registry.HARD_DELETE_ENABLED}")
update `HARD_DELETE_ENABLED` with small case

2023-06-26 11:58 UTC, varadeth commented on java/registry/src/main/java/dev/sunbirdrc/registry/service/impl/RegistryServiceImpl.java
> +                    if (isElasticSearchEnabled()) {
this if block can be places outside of if-else statments since this is common to both

2023-06-26 11:58 UTC, varadeth commented on java/registry/src/main/java/dev/sunbirdrc/registry/service/impl/RegistryServiceImpl.java
> -    @Override
please remove this change

2023-06-26 11:58 UTC, varadeth commented on java/registry/src/main/java/dev/sunbirdrc/registry/service/impl/RegistryServiceImpl.java
> +    public ESMessage esMessage;
is this used in this class?

2023-06-26 11:58 UTC, varadeth commented on java/registry/src/main/resources/application.yml
> +  providerName: ${search_providerName:dev.sunbirdrc.registry.service.SearchService}
remove this change

2023-06-26 11:58 UTC, varadeth commented on java/registry/src/main/resources/application.yml
> +
remove this new lines

2023-06-26 11:58 UTC, varadeth commented on java/registry/src/main/java/dev/sunbirdrc/registry/service/FileStorageService.java
> +	public DocumentsResponse updateFiles(MultipartFile[] files, String requestedURI) {
this is part of another Pull Request
we don't need this here
changes of this complete file can be removed

2023-06-26 11:58 UTC, varadeth commented on java/registry/src/main/java/dev/sunbirdrc/registry/dao/IRegistryDao.java
> +import java.util.UUID;
this import can be removed

2023-06-26 11:58 UTC, varadeth commented on java/registry/src/main/java/dev/sunbirdrc/registry/controller/RegistryEntityController.java
> +@RestController //used to create restfull web servces, it takes care of mapping request data
remove this comments

2023-06-26 11:58 UTC, varadeth commented on java/registry/src/main/java/dev/sunbirdrc/registry/controller/FileStorageController.java
> +    @PutMapping("/api/v1/{entity}/{entityId}/{property}/documents/{documentId}")
this file should not be a part of this pull request

2023-06-26 11:58 UTC, varadeth commented on java/registry/src/main/java/dev/sunbirdrc/registry/config/GenericConfiguration.java
> +	@Value("${registry.HARD_DELETE_ENABLED}")
replace `HARD_DELETE_ENABLED` with small case

2023-06-26 11:58 UTC, varadeth commented on java/registry/src/main/java/dev/sunbirdrc/registry/controller/RegistryEntityController.java
> +             Vertex deletedEntity = registryHelper.deleteEntity(entityId, userId);
refactor this code block. looks some logic is duplicated

2023-06-26 11:58 UTC, varadeth commented on java/registry/src/main/java/dev/sunbirdrc/registry/controller/RegistryEntityController.java
> +        return new ResponseEntity<>(response, HttpStatus.OK);//The method returns a ResponseEntity object with the response body and HTTP status code.
remove all the comments from class

2023-06-26 11:58 UTC, varadeth commented on java/registry/src/main/java/dev/sunbirdrc/registry/dao/RegistryDaoImpl.java
> +
remove comments and empty lines

2023-06-29 11:38 UTC, chopadetejaswini commented
made all the commented changes in PR and updated PR

2023-06-30 14:08 UTC, varadeth requested changes

2023-06-30 14:08 UTC, varadeth commented on java/registry/src/main/java/dev/sunbirdrc/registry/controller/RegistryEntityController.java
> +          }
logic still doesn't look correct. could you please remove duplicate code/logic

2023-07-31 09:26 UTC, holashchand requested changes

2023-07-31 09:26 UTC, holashchand commented on java/registry/src/main/java/dev/sunbirdrc/registry/controller/RegistryEntityController.java
> +                registryHelper.revokeExistingCredentials(entityName, entityId, userId, signedData);
Why revoking credentials again? In above steps revoke credentials is already there

2023-07-31 09:46 UTC, chopadetejaswini commented
Done with the change

2023-07-31 11:11 UTC, holashchand requested changes

2023-07-31 11:11 UTC, holashchand commented on java/registry/src/main/java/dev/sunbirdrc/registry/dao/RegistryDaoImpl.java
> +    private DataSource dataSource;
this is unused. you should remove

2023-07-31 11:11 UTC, holashchand commented on java/registry/src/main/java/dev/sunbirdrc/registry/helper/RegistryHelper.java
> +    public Vertex deleteEntity(String entityName, String entityId, String userId) throws Exception {
ensure for all the places this method is used, you are passing entity name

2023-07-31 11:11 UTC, holashchand commented on java/registry/src/main/java/dev/sunbirdrc/registry/service/impl/RegistryServiceImpl.java
>                          callESActors(null, "DELETE", index, uuid, tx);
move this out of if condition, don't duplicate in if and else

2023-07-31 11:11 UTC, holashchand commented on java/registry/src/main/resources/application.yml
> +  hard_delete_enabled: true
set default to false and use environment variable

2023-07-31 11:11 UTC, holashchand commented on java/sunbirdrc-actors/src/main/java/dev/sunbirdrc/actors/ElasticSearchActor.java
> +    }*/
remove commented code

2023-10-11 09:28 UTC, holashchand requested changes

2023-10-11 09:28 UTC, holashchand commented on docker-compose.yml
> -      - sign_url=http://certificate-signer:8079/sign
rollback this change

2023-10-11 09:28 UTC, holashchand commented on java/elastic-search/src/main/java/dev/sunbirdrc/elastic/ESMessage.java
revert changes in this file, not require any change

2023-10-11 09:28 UTC, holashchand commented on java/registry/src/main/java/dev/sunbirdrc/registry/controller/FileStorageController.java
revert this file changes

2023-10-11 09:28 UTC, holashchand commented on java/registry/src/main/java/dev/sunbirdrc/registry/dao/RegistryDaoImpl.java
> +import javax.sql.DataSource;
revert this change

2023-10-11 09:28 UTC, holashchand commented on java/registry/src/main/java/dev/sunbirdrc/registry/service/FileStorageService.java
revert this file changes

2023-10-11 09:28 UTC, holashchand commented on java/registry/src/main/java/dev/sunbirdrc/registry/service/impl/RegistryServiceImpl.java
> -    @Override
remove this change

2023-10-11 09:28 UTC, holashchand commented on java/registry/src/main/resources/application.yml
remove this empty line

2023-10-11 09:28 UTC, holashchand commented on java/sunbirdrc-actors/src/main/java/dev/sunbirdrc/actors/ElasticSearchActor.java
revert this file changes

2023-10-12 06:52 UTC, chopadetejaswini commented on java/registry/src/main/java/dev/sunbirdrc/registry/controller/FileStorageController.java
Done

2023-10-12 06:53 UTC, chopadetejaswini commented on java/registry/src/main/java/dev/sunbirdrc/registry/service/FileStorageService.java
Done

2023-10-12 06:53 UTC, chopadetejaswini commented on java/sunbirdrc-actors/src/main/java/dev/sunbirdrc/actors/ElasticSearchActor.java
Done

2023-10-20 09:39 UTC, holashchand commented
Please check why the build is failing

2023-10-25 12:15 UTC, chopadetejaswini commented
> Please check why the build is failing

Not able to check

2024-01-25 12:29 UTC, closed without merging