[Issue-789] Fixed Native Search doesn't return complete object issue - 2.0
Sunbird-RC/sunbird-rc-core pull request #295
Opened 2024-03-08 07:04 UTC by shiva-beehyv

2024-03-15 06:09 UTC, Sreejit-K approved these changes

2024-03-15 08:45 UTC, holashchand commented
Multiple search operators not working
i.e
```
{
  "offset": 0,
  "limit": 2,
  "filters": {
    "policyDetails": {
        "policyNumber": {
            "contains": "insurance10"
        }
    },
    "mobile": {
        "contains": "insurance101"
    }
  }
}
```

2024-03-15 11:22 UTC, holashchand approved these changes

2024-03-15 11:22 UTC, holashchand commented
creating a new ticket for the issue i mentioned above

2024-03-15 11:29 UTC, holashchand commented
@shiva-beehyv we should create the PR for main branch

2024-03-28 08:50 UTC, holashchand requested changes

2024-03-28 08:50 UTC, holashchand commented on .github/workflows/maven.yml
> +    - name: Setup upterm session
comment this change or revert

2024-03-28 12:40 UTC, shiva-beehyv commented
Closing this ticket since the initial branching off was done from a wrong branch.
Creating [another pr](https://github.com/Sunbird-RC/sunbird-rc-core/pull/303/commits)

2024-03-28 12:40 UTC, closed without merging